### ISSUE TITLE
Error while installing the copy of lua 

### ISSUE THREAD

**Issue by loulavorel** [sevenhugs/smart-remote-sdk#1]
Hi,

I runned into an error when I tried to install a local copy of lua and its librairies with the advised command:
`make -C lib/lua install`

Here is a copy of the error I got:
`lua.c:80:31: fatal error: readline/readline.h: No such file or directory`
`#include <readline/readline.h>`

Any idea, please ?

**Comment by nschodet-sevenhugs** [comment]
You need development files for libreadline, what OS are you running?

**Comment by loulavorel** [comment]
Ubuntu.

Where could I find such files ?

**Comment by nschodet-sevenhugs** [comment]
You can run: `sudo apt-get install libreadline-dev`, this should install the missing files.

**Comment by loulavorel** [comment]
Ubuntu, ok I'm going to install the readline packages. Thank you

**Comment by nschodet-sevenhugs** [comment]
You're welcome, I added a note in the README file about the problem.
