### ISSUE TITLE
Bad request error when processing a second http request

### ISSUE THREAD

**Issue by loulavorel** [sevenhugs/smart-remote-sdk#2]
Hi there,

I'm still trying to handle your prototype but I got stuck on a new issue and will need a little help to fix it. 
Basically, I need to login to my service (in order to get a Session ID) before doing query or set requests and then logout. I implemanted enough code to run all of these requests independantly (providing a Session ID for query and set) but I would like to be able to run them all with only one call.

```
c = cc(params)
http.run()
c:login(common.ui)
http.run()
if command then
  c[command](c, common.ui, table.unpack(command_args))
  http.run()
end
c:query(common.ui)
http.run()
c:logout()
http.run()

```

Here comes the problem, the first http request (the login one) is completed and I retrieve a Session ID. I used this ID to change the headers['Cookie'] but when it comes to the query request, this one fails:

```
HTTP/1.1 400 Bad Request
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>400 Bad Request</title>
</head><body>
<h1>Bad Request</h1>
<p>Your browser sent a request that this server could not understand.<br />
</p>
</body></html>
```

However, if I skip the login request and hard-code a Session ID, the query request will succeed.

I'm not familiar with lua but it might be trivial for you ... In your test_hue.lua example your two requests (set and query) come one after the other so you might be able to help me with this.

Thank you

**Comment by nschodet-sevenhugs** [comment]
You can chain several requests, to do this, just issue the second request in the `done` callback. You can see an example of this in the sonos control script, in the query method.

I hope I understood correctly your problem. Could you show your control script?

**Comment by loulavorel** [comment]
I fixed it by getting inspiration from the sonos control scrip as you advised it ! Thank you for your help

**Comment by nschodet-sevenhugs** [comment]
You're welcome. I close the ticket then.
